platform :ios, 8.0
use_frameworks!
target 'WQBasicModules_Example' do
  pod 'WQBasicModules', :path => '../'

  target 'WQBasicModules_Tests' do
    inherit! :search_paths
#    inhibit_all_warnings!
#    pod 'WQBasicModules', :path => '../'
#    pod 'Quick', '~> 1.2.0', :inhibit_warnings => true
#    pod 'Nimble', '~> 7.0.2', :inhibit_warnings => true
#    pod 'FBSnapshotTestCase' , '~> 2.1.4', :inhibit_warnings => true
#    pod 'Nimble-Snapshots' , '~> 6.3.0', :inhibit_warnings => true
  end
end
