platform :ios, 10.0
use_modular_headers!
install! 'cocoapods', :warn_for_unused_master_specs_repo => false
target 'WQBasicModules_Example' do
#  warn_for_unused_master_specs_repo => false
  
  pod 'WQBasicModules', :path => '../'
  pod 'WQBasicModules/FunModule/ImagePicker', :path => '../'
#  pod 'WQBasicModules/Beta/TransitionStyle', :path => '../'
#  pod 'SnapKit'
#  pod 'SwiftLint', :configuration => 'Debug'
  target 'WQBasicModules_Tests' do
    inherit! :search_paths
#    inhibit_all_warnings!
#    pod 'WQBasicModules', :path => '../'
#    pod 'Quick', '~> 1.2.0', :inhibit_warnings => true
#    pod 'Nimble', '~> 7.0.2', :inhibit_warnings => true
#    pod 'FBSnapshotTestCase' , '~> 2.1.4', :inhibit_warnings => true
#    pod 'Nimble-Snapshots' , '~> 6.3.0', :inhibit_warnings => true
  end
end
