os: osx
osx_image: xcode11.4
language: swift
before_install:
- openssl aes-256-cbc -K $encrypted_d7555cc223fe_key -iv $encrypted_d7555cc223fe_iv
  -in profiles/id_rsa.enc -out ~\/.ssh/id_rsa -d
- "./scripts/config.sh"
install:
- bundle install
script:
- fastlane trunk tag:0.3.4
