# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.4
language: Swift 
install:
  - bundle install
script:
  - fastlane trunk
# cache: cocoapods
# podfile: Example/Podfile
# env: 
#   - APP_NAME="WQBasicModules"
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
# script:
# - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/WQBasicModules.xcworkspace -scheme WQBasicModules-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint
